region          = "us-east-1"
environment     = "dev"
acm_domain_name = "*.sourcef.us"
#container_image = "757583164619.dkr.ecr.us-east-1.amazonaws.com/sf-refarch-dev-sourcefuse-backstage:0.3.8"
namespace    = "arc-iac-sf"
project_name = "arc-training"
